name: Build Dylib

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compile iOS dylib
        run: |
          clang -dynamiclib -arch arm64 \
            -isysroot $(xcrun --sdk iphoneos --show-sdk-path) \
            -miphoneos-version-min=14.0 \
            DisableSiri.m -o DisableSiri.dylib

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: DisableSiri-dylib
          path: DisableSiri.dylib

